### ISSUE TITLE
ping pong game

### ISSUE THREAD

**Issue by babajane777** [Ayush-Kanduri/Ping-Pong-Game-using-Javascript#1]
while importing paddle.js,error is coming like
"Uncaught SyntaxError: Cannot use import statement outside a module (at script.js:1:1)"

**Comment by Ayush-Kanduri** [comment]
If you're using NodeJS :
- Try replacing "import" with "require".
Example: const Paddle = require("./Paddle.js");

Instead of export default class Paddle {}, use module.exports = Paddle class 

- If it doesn't work, Add "type": "module" to your package.json file.
{
  // ...
  "type": "module",
  // ...
}

- Add type="module" to the script loader.
<script type="module" src="script.js" type="module"></script>
